---
- hosts: 127.0.0.1
  remote_user: root
  roles:
    - role: azavea.scala
      scala_version: 2.11.7
      java_oracle_accept_license_agreement: true
      scala_sbt_version: 0.13.9
      java_version: 8u72+8u71arm-1~webupd8~0
      java_major_version: 8
      java_flavor: oracle
  tasks:
    - name: install git
      apt:
        pkg=git
        force=yes
        update_cache=yes
      with_items:
        - git
        - vim
    - name: fetch source code for location server
      git: 
        repo="https://github.com/whereat/whereat-location-server.git"
        dest="/whereat-location-server"